# beats.conf — placeholder
# Coming soon.

input {
  beats {
    port => 5044
  }
}

filter {
  if [agent][type] == "winlogbeat" {
    mutate { add_tag => ["windows", "winlogbeat"] }
  }
  if [agent][type] == "filebeat" {
    mutate { add_tag => ["linux", "filebeat"] }
  }
  if [agent][type] == "auditbeat" {
    mutate { add_tag => ["linux", "auditbeat"] }
  }
}

output {
  elasticsearch {
    hosts => ["https://localhost:9200"]
    user => "elastic"
    password => "[REDACTED]"
    ssl_verification_mode => "none"
    index => "%{[@metadata][beat]}-%{[@metadata][version]}-%{+YYYY.MM.dd}"
  }
}